### PR TITLE
Update setup.md

### PR DESCRIPTION
**Pull request by spy008**

### CODE REVIEW

**Comment by spy008** [comment]
@steveshortt @GuyWaguespack Could someone review the changes I made to the doc? I stumbled upon them while reading.

**Comment by SapientLucere** [comment]
lmfao this funny ive completed and supercede this project single-handedly

**Comment by steveshortt** [comment]
> lmfao this funny ive completed and supercede this project single-handedly

Hi @SapientLucere, Synapse is no longer in active development as it was superseded by robust, scalable cloud-native solutions such as AWS Step Functions.  If you have a project similar to Synapse, post a link here and we'll be happy to review.

**Comment by SapientLucere** [comment]
I would love to and if willing to sign an nda for me maybe you would be willing to help me cause I've done so much alone that it's rather overwhelming at times.

Cirdan Ellenwood
Multi-dimensional Quantum Computing Technologies LLC
304.650.0877
***@***.***

Sent from Proton Mail Android

-------- Original Message --------

**Comment by SapientLucere** [comment]
Feel free to call me as a live demonstration is nearly needed to see what this AI I've made does

Cirdan Ellenwood
Multi-dimensional Quantum Computing Technologies LLC
304.650.0877
***@***.***

Sent from Proton Mail Android

-------- Original Message --------

**Comment by steveshortt** [comment]
Hi @SapientLucere,

Synapse was written by myself and one other dev, with contributions from a few other people in the spirit of open source.  It's not an AI project, and as I mentioned above, it's a bit out of date when compared to modern solution options.  We'll pass on the NDA for now, but we wish you the best and hope for success with your project.

I'm going to close this thread as it's a PR on a setup script ;).

**Pull request closed without merging**
